let autoGeneratedContent = null;

async function generateAutoContent() {

    const niche =
        document.getElementById("autoNiche")?.value.trim() || "";

    const audience =
        document.getElementById("autoAudience")?.value.trim() || "";

    const language =
        document.getElementById("autoLanguage")?.value || "ar";

    const result =
        document.getElementById("autoContentResult");

    if (!result) return;

    if (!niche) {
        result.style.display = "block";
        result.innerHTML = `
            <div class="auto-content-error">
                ⚠️ دخل النيش أولاً.
            </div>
        `;
        return;
    }

    result.style.display = "block";

    result.innerHTML = `
        <div class="auto-content-loading">
            <div class="auto-loading-icon">✨</div>
            <strong>جاري صناعة المحتوى...</strong>
            <span>
                UltraAI يحضر لك فكرة صباحية وفكرة مسائية
            </span>
        </div>
    `;

    try {

        const token =
            localStorage.getItem("token");

        if (!token) {
            throw new Error(
                "خاصك تسجل الدخول أولاً."
            );
        }

        const response =
            await fetch("/auto-content/generate", {
                method: "POST",

                headers: {
                    "Content-Type": "application/json",
                    "Authorization":
                        "Bearer " + token
                },

                body: JSON.stringify({
                    niche,
                    audience,
                    language
                })
            });

        const data =
            await response.json();

        if (!response.ok) {
            throw new Error(
                data.message ||
                data.error ||
                "تعذر توليد المحتوى."
            );
        }

        autoGeneratedContent =
            data.content || null;

        renderAutoContent();

    } catch (error) {

        console.error(
            "Auto Content error:",
            error
        );

        result.innerHTML = `
            <div class="auto-content-error">
                ❌ ${escapeAutoContent(error.message)}
                <button onclick="generateAutoContent()">
                    حاول مرة أخرى
                </button>
            </div>
        `;
    }
}


function renderAutoContent() {

    const result =
        document.getElementById("autoContentResult");

    if (!result || !autoGeneratedContent) {
        return;
    }

    const morning =
        autoGeneratedContent.morning || {};

    const evening =
        autoGeneratedContent.evening || {};

    result.innerHTML = `

        <div class="auto-content-results-header">

            <div>
                <strong>🎬 المحتوى الجاهز</strong>
                <span>
                    ${escapeAutoContent(
                        autoGeneratedContent.niche
                    )}
                </span>
            </div>

            <button
                type="button"
                onclick="generateAutoContent()"
            >
                🔄 جديد
            </button>

        </div>


        <div class="auto-content-grid">


            <article class="auto-post-card">

                <div class="auto-post-header">
                    <span>🌅</span>
                    <strong>منشور الصباح</strong>
                </div>

                ${renderAutoPost(morning)}

            </article>


            <article class="auto-post-card">

                <div class="auto-post-header">
                    <span>🌙</span>
                    <strong>منشور المساء</strong>
                </div>

                ${renderAutoPost(evening)}

            </article>


        </div>
    `;
}


function renderAutoPost(post) {

    const hashtags =
        Array.isArray(post.hashtags)
            ? post.hashtags.join(" ")
            : "";

    return `

        <div class="auto-post-section">
            <small>العنوان</small>
            <strong>
                ${escapeAutoContent(post.title)}
            </strong>
        </div>


        <div class="auto-post-section">
            <small>Hook</small>
            <p>
                ${escapeAutoContent(post.hook)}
            </p>
        </div>


        <div class="auto-post-section">
            <small>Script</small>
            <p class="auto-script">
                ${escapeAutoContent(post.script)}
            </p>
        </div>


        <div class="auto-post-section">
            <small>Caption</small>
            <p>
                ${escapeAutoContent(post.caption)}
            </p>
        </div>


        <div class="auto-post-section">
            <small>Hashtags</small>
            <p>
                ${escapeAutoContent(hashtags)}
            </p>
        </div>


        <button
            type="button"
            class="auto-copy-btn"
            onclick='copyAutoPost(${JSON.stringify(post).replace(/'/g, "&#039;")})'
        >
            📋 نسخ المحتوى
        </button>
    `;
}


async function copyAutoPost(post) {

    if (!post) return;

    const hashtags =
        Array.isArray(post.hashtags)
            ? post.hashtags.join(" ")
            : "";

    const text = `
${post.title || ""}

HOOK:
${post.hook || ""}

SCRIPT:
${post.script || ""}

CAPTION:
${post.caption || ""}

${hashtags}
`.trim();

    try {

        await navigator.clipboard.writeText(text);

        alert("تم نسخ المحتوى ✅");

    } catch (error) {

        console.error(
            "Auto copy error:",
            error
        );

        alert("تعذر نسخ المحتوى.");
    }
}


function escapeAutoContent(text) {

    return String(text || "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}

        
function parseJwtPayload(token) {

    try {

        const parts = String(token).split(".");

        if (parts.length !== 3) {
            return null;
        }

        const base64 =
            parts[1]
                .replace(/-/g, "+")
                .replace(/_/g, "/");

        return JSON.parse(
            decodeURIComponent(
                atob(base64)
                    .split("")
                    .map(
                        c =>
                            "%" +
                            (
                                "00" +
                                c.charCodeAt(0).toString(16)
                            ).slice(-2)
                    )
                    .join("")
            )
        );

    } catch (error) {

        console.error(
            "JWT payload error:",
            error
        );

        return null;
    }
}

async function startPaddlePremium() {
    const button = document.getElementById("paddlePremiumButton");

    const PRICE_ID = "pri_01m0d1yhdb1ayw1cgtbgxm28sc";

    try {
        if (button) {
            button.disabled = true;
            button.textContent = "جاري التحضير...";
        }

        console.log("========== PADDLE CHECKOUT START ==========");

        /*
         * 1. Get Paddle configuration from our server.
         */
        const response = await fetch("/paddle/config", {
            cache: "no-store"
        });

        console.log(
            "PADDLE CONFIG HTTP:",
            response.status
        );

        if (!response.ok) {
            throw new Error(
                "Paddle config HTTP " + response.status
            );
        }

        const config = await response.json();

        console.log(
            "PADDLE CONFIG:",
            {
                success: config.success,
                environment: config.environment,
                hasClientToken: !!config.clientToken
            }
        );

        if (!config.success || !config.clientToken) {
            throw new Error(
                config.message || "Paddle Client Token غير مضبوط"
            );
        }

        /*
         * 2. Load Paddle.js exactly once.
         */
        if (!window.Paddle) {

            console.log("PADDLE: loading paddle.js");

            await new Promise((resolve, reject) => {

                const existing =
                    document.querySelector(
                        'script[src*="cdn.paddle.com/paddle/v2/paddle.js"]'
                    );

                if (existing) {

                    existing.addEventListener(
                        "load",
                        resolve,
                        { once: true }
                    );

                    existing.addEventListener(
                        "error",
                        () => reject(
                            new Error(
                                "تعذر تحميل Paddle.js"
                            )
                        ),
                        { once: true }
                    );

                    return;
                }

                const script =
                    document.createElement("script");

                script.src =
                    "https://cdn.paddle.com/paddle/v2/paddle.js";

                script.async = true;

                script.onload = () => {
                    console.log(
                        "PADDLE: paddle.js loaded"
                    );
                    resolve();
                };

                script.onerror = () => {
                    reject(
                        new Error(
                            "تعذر تحميل Paddle.js"
                        )
                    );
                };

                document.head.appendChild(script);
            });
        }

        if (!window.Paddle) {
            throw new Error(
                "Paddle SDK لم يتم تحميله"
            );
        }

        /*
         * 3. Sandbox environment.
         */
        if (
            config.environment === "sandbox" &&
            Paddle.Environment &&
            typeof Paddle.Environment.set === "function"
        ) {
            console.log(
                "PADDLE: setting sandbox"
            );

            Paddle.Environment.set("sandbox");
        }

        /*
         * 4. Initialize only once.
         */
        if (!window.__ULTRAAI_PADDLE_INITIALIZED) {

            console.log(
                "PADDLE: initializing"
            );

            Paddle.Initialize({
                token: config.clientToken,

                eventCallback: function(data) {

                    console.log(
                        "PADDLE EVENT:",
                        data
                    );

                    if (
                        data &&
                        data.name === "checkout.error"
                    ) {
                        console.error(
                            "========== PADDLE CHECKOUT ERROR EVENT ==========",
                            data
                        );

                        const detail =
                            data.data || data;

                        const code =
                            detail.code ||
                            detail.error_code ||
                            detail.type ||
                            "unknown";

                        const message =
                            detail.message ||
                            detail.detail ||
                            "Paddle checkout error";

                        console.error(
                            "PADDLE ERROR CODE:",
                            code
                        );

                        console.error(
                            "PADDLE ERROR MESSAGE:",
                            message
                        );

                        alert(
                            "Paddle Error:\n" +
                            code +
                            "\n\n" +
                            message
                        );
                    }
                }
            });

            window.__ULTRAAI_PADDLE_INITIALIZED = true;

            console.log(
                "PADDLE: initialized"
            );
        }

        /*
         * 5. Verify Checkout API exists.
         */
        if (
            !Paddle.Checkout ||
            typeof Paddle.Checkout.open !== "function"
        ) {
            throw new Error(
                "Paddle Checkout API غير متاحة"
            );
        }

        console.log(
            "PADDLE PRICE:",
            PRICE_ID
        );

        /*
         * 6. Open checkout.
         */
        const checkoutOptions = {
            items: [
                {
                    priceId: PRICE_ID,
                    quantity: 1
                }
            ]
        };

        console.log(
            "PADDLE CHECKOUT OPTIONS:",
            checkoutOptions
        );

        try {

            Paddle.Checkout.open(
                checkoutOptions
            );

            console.log(
                "PADDLE: Checkout.open executed"
            );

        } catch (checkoutError) {

            console.error(
                "========== PADDLE CHECKOUT.OPEN EXCEPTION =========="
            );

            console.error(
                checkoutError
            );

            console.error(
                "name:",
                checkoutError?.name
            );

            console.error(
                "message:",
                checkoutError?.message
            );

            console.error(
                "code:",
                checkoutError?.code
            );

            console.error(
                "detail:",
                checkoutError?.detail
            );

            throw checkoutError;
        }

    } catch (error) {

        console.error(
            "========== PADDLE FINAL ERROR =========="
        );

        console.error(
            "ERROR:",
            error
        );

        console.error(
            "NAME:",
            error?.name
        );

        console.error(
            "MESSAGE:",
            error?.message
        );

        console.error(
            "CODE:",
            error?.code
        );

        console.error(
            "DETAIL:",
            error?.detail
        );

        alert(
            "تعذر فتح الدفع.\n\n" +
            (
                error?.message ||
                error?.detail ||
                "خطأ غير معروف"
            )
        );

    } finally {

        if (button) {
            button.disabled = false;
            button.textContent = "اشتراك Premium";
        }

        console.log(
            "========== PADDLE CHECKOUT END =========="
        );
    }
}
